ruby '2.5.0'
source 'https://rubygems.org'

#gem 'nanoc', '3.6.7'
gem 'nanoc', '~> 4.9', '>= 4.9.2'

#gem 'kramdown', '1.3.1'
gem 'kramdown', '~> 1.16', '>= 1.16.2'

#gem 'adsf', '1.2.0'
gem 'adsf', '~> 1.4', '>= 1.4.1'

#gem 'pygments.rb', '0.5.4'
gem 'pygments.rb', '~> 1.2', '>= 1.2.1'

#gem 'nokogiri', '1.6.3.1'
gem 'nokogiri', '~> 1.8', '>= 1.8.2'

#gem 'httparty'
gem 'httparty', '~> 0.16.2'

#gem 'rainpress', '1.0'
gem 'rainpress', '~> 1.0', '>= 1.0.1'

#gem 'guard-nanoc', '1.0.2'
gem 'guard-nanoc', '~> 2.1', '>= 2.1.2'

#gem 'builder', '3.2.2'
gem 'builder', '~> 3.2', '>= 3.2.3'